import '@fortawesome/fontawesome-free/css/all.css';
import { MotionPlugin } from '@vueuse/motion';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import { createApp } from 'vue';
import Vue3Lottie from 'vue3-lottie';
import Particles from 'vue3-particles';
import App from './App.vue';
import './index.css';
const app = createApp(App);
app.use(Particles);
app.use(MotionPlugin);
app.use(Vue3Lottie);
app.use(ElementPlus);
app.mount('#app');
